---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: warpland
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/tofik/nwg-shell/repo/fedora-%OS_VERSION%/tofik-nwg-shell-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/pgdev/ghostty/repo/fedora-%OS_VERSION%/pgdev-ghostty-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/peterwu/iosevka/repo/fedora-%OS_VERSION%/peterwu-iosevka-fedora-%OS_VERSION%.repo
    install:
      -  GraphicsMagick
      -  ImageMagick
      -  bat
      -  blueman
      -  brightnessctl
      -  btrbk
      -  cargo
      -  cliphist
      -  copyq
      -  fd
      -  feh
      -  "@gnome-desktop"
      -  hyprdim
      -  hypridle
      -  hyprland
      -  hyprland-plugin-hyprbars
      -  hyprlock
      -  hyprlock
      -  hyprpaper
      -  hyprshot
      -  hyprsunset
      -  iosevka-etoile-fonts
      -  jetbrains-mono-fonts-all
      -  jq
      -  lsd
      -  micro
      -  mpv
      -  network-manager-applet
      -  nwg-clipman
      -  nwg-drawer
      -  nwg-shell-config
      -  python-psutil
      -  qt5-qtwayland
      -  qt5ct
      -  qt6-qtwayland
      -  qt6ct
      -  restic
      -  rsms-inter-fonts
      -  rsms-inter-vf-fonts
      -  satty
      -  starship
      -  stow
      -  swaync
      -  swww
      -  udiskie
      -  uwsm
      -  vips
      -  waybar
      -  waypaper
      -  wl-clipboard
      -  wl-copy
      -  wl-paste
      -  wlogout
      -  xwaylandvideobridge
      -  zoxide
      
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - org.mozilla.firefox
        - org.gnome.Loupe
      remove:
        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

